### ISSUE TITLE
Ubuntu 12.04.4

### ISSUE THREAD

**Issue by bonelifer** [kgroeneveld/tv_grab_sd_json#1]
I get this after entering credentials:

This step configures the lineups enabled for your Schedules Direct account. It impacts all other configurations and programs using the JSON API with your account. A maximum of 4 lineups can by added to your account. In a later step you will choose which lineups or channels to actually use for this configuration.
Current lineups enabled for your Schedules Direct account:
Use of uninitialized value in concatenation (.) or string at /usr/local/bin/tv_grab_na_sd_json line 349.
Use of uninitialized value in concatenation (.) or string at /usr/local/bin/tv_grab_na_sd_json line 349.
1.  | QAM |  | USA-AR03460-QAM
Edit account lineups [continue,add,delete (default=continue)] 

Other than those two lines, the config file was saved and I was able to fetch.

**Comment by kgroeneveld** [comment]
Thanks for the feedback.  I tried adding that same lineup to my account and received similar errors.  I have just pushed up a change which I think fixes the issue.

I had never tested a QAM lineup before.  To be honest I am not even sure what a QAM lineup really is other than I know what the acronym stands for. Personally I am only using OTA lineups.

**Comment by bonelifer** [comment]
From the SD forum: http://forums.schedulesdirect.org/viewtopic.php?p=7768#p7768  Basically a lineup that includes the exact Clear QAM(unencrypted) channel scan for a cable lineup. Something a user would have to provide since cable co's aren't going to be that helpful.

**Comment by bonelifer** [comment]
After "git pull" and copying the file, I get this on a bad password:
https://gist.github.com/bonelifer/95b7f2750915cf0192a3

I've obviously removed my username and replaced it with "myUsername". With the correct password, the previous error is gone now.

**Comment by kgroeneveld** [comment]
I already knew about the error when an invalid username and/or password is used.  It falls under the "Currently very little error checking is performed. If something goes wrong you will likely get a cryptic error and/or perl exception." TODO item listed in the brief documentation near the top of the  tv_grab_na_sd_json file.  You will get similar errors if you enter an invalid zip/postal code or in almost any case that the server does not return a success code.  I need to start trapping these errors, show a more friendly message and try to recover if possible.
