### ISSUE TITLE
Grabber and Channel numbers with QAM lineups

### ISSUE THREAD

**Issue by bonelifer** [kgroeneveld/tv_grab_sd_json#2]
Is it possible to get the channel number with the json feed? Here's the output for the dd and sd-json for AMC:
https://gist.github.com/bonelifer/296a51345c0970b5ae9a

**Comment by kgroeneveld** [comment]
There are channel numbers in the JSON feed.  As there isn't a channel number field in the XMLTV schema I wasn't sure what to do with it.  Thanks for posting the comparison with the dd grabber which shows how it is handling channel numbers.  Hopefully in the near future I can do something similar.

I really should be comparing to the dd grabber output myself.  I have never even tried running the dd grabber yet!  I previously only used the dd grabber built into MythTV and not the XMLTV grabber.

**Comment by kgroeneveld** [comment]
The channel number is now (and has been for a quote some time) in the third display-name tag.
