### ISSUE TITLE
Long Programs in Progress not being grabbed

### ISSUE THREAD

**Issue by kyl416** [kgroeneveld/tv_grab_sd_json#4]
Whenever there's a long program currently in progress like movies, sporting events, or extended blocks like news, music videos, or SIGN OFF, it doesn't get grabbed, instead the grabber starts with the next program scheduled to air on that channel.

Is there anyway you can have it grab the entire current day like tv_grab_na_dd does?

**Comment by kgroeneveld** [comment]
I just pushed a small change which should fix this.  I knew about this issue but had forgotten about it.  Thanks for reporting it.
