### ISSUE TITLE
Use of uninitialized value in sprintf at tv_grab_sd_json line 923

### ISSUE THREAD

**Issue by fnxweb** [kgroeneveld/tv_grab_sd_json#7]
Started seeing this with an old nightly a couple of days ago.  Latest nightly from xmltv still does it.

When the error occurs:
stationID=75804, $channel->{'stationID'} appears to not be set?
        # mythtv seems to assume that the first three display-name elements are
        # name, callsign and channel number. We follow that scheme here.
        $ch{'id'} = sprintf($channel_id_format, $channel->{'stationID'});

Oh yes, and a typo:  “Removing old cache entires...”.

**Comment by kgroeneveld** [comment]
I have found that if the config file contains a channel that is not in one of your enabled lineups then this error can occur.  This could happen if the config was edited manually with an invalid entry or the channel was removed from the lineup by SD.  If have committed a fix which gives a more helpful message in this case and prevents the invalid channel data from being in the XML output.

And I also fixed the typo.

**Comment by fnxweb** [comment]
Cool, great!

Actually, that's interesting, I did have to manually transcode the full channel line-up down to the channels I have set up. This could be one I mistyped. I'll have to check in the morning.

Thanks!

**Comment by fnxweb** [comment]
OK, well I've checked my lineups, and the channel does exist.  Using the Chrome Postman tool to interrogate SD with my login, for my Satellite lineup (https://json.schedulesdirect.org/20141201/lineups/GBR-0001172-DEFAULT) I get:
 **In the initial map section (reformatted JSON)**
      {
         "stationID":"75804",
         "channel":"140"
      },
 **Later on in stations:**
      {
         "stationID":"75804",
         "name":"4Seven",
         "callsign":"4SEVEN",
         "broadcastLanguage":[
            "en-GB"
         ],
         "descriptionLanguage":[
            "en-GB"
         ],
         "logo":{
            "URL":"https:\/\/s3.amazonaws.com\/schedulesdirect\/assets\/stationLogos\/s75804_h3_aa.png",
            "height":270,
            "width":360,
            "md5":"c0114bcdc45e19ef057404"
         }
      },

So I don't _think_ anything's set up wrong.  I'll can't attach the full JSON dump compressed, github won't have it, and it's a bit big as text (~290KB).  I don't mind emailing it if you think it'll help.

**Comment by kgroeneveld** [comment]
I tried adding GBR-0001172-DEFAULT to my account and created a configuration with channel 75804 and a couple other channels.  I cannot reproduce the error.

Maybe if you sent me your config file (minus the password) I could see the problem.  But I suspect maybe the contents of your cache file have maybe become corrupted somehow?  You could try moving/renaming your cache file to see if the problem goes away.  Although in that case it would still be nice to figure out what is wrong to help prevent it in the future.  If you have somewhere you can upload your cache file I could download it and test with it.

**Comment by fnxweb** [comment]
How odd.  I get a successful run as well if I have a config file with only that channel in it.  But if I go back to the full-fat config., I get the problem.  Maybe I'm misinterpreting my debug and it's not that channel but one next to it?  I only had time to do those two runs this morning, so I've not been able to break it down more.

I have copied my last cache, full sanitised config. file and modified grabber (one extra line for debug) to:

[https://www.fnxweb.co.uk/fnx/data/tv_grab_sd_json/](url)

I'll delete it when I know you've grabbed a copy.

If I remember when I get in, I'll try doing some more runs to pin down a minimal config. file, since this one takes several minut4s to run with its channel count.

(An aside: this has both my lineup subs in, one terrestrial one satellite;  the channel list is my Satellite one, since I have to do a separate run for each due to the way mythfilldatabase works [each is a separate “source”].  Will having both `channels=` lines in add unnecessary load - indeed, will it go wrong if I only have the one `channels=` but wish to retain both subs?  I create the config. on the fly upon fetching listings from a fixed header [with login and subs, _etc._] and the channel IDs for the given source in the MythTV database)

**Comment by fnxweb** [comment]
OK, I reproduced the warning with the config file linked to reduced to just the channel in question (75804) and the one after it. So I then tried _just_ the one after it, and lo and behold I got the warning;  I really must have been misinterpreting the debug :-/

The problem channel is 82432 (Euronews) which I _think_ I should have (will check shortly) but isn't in the SD feed for my lineups any more (the channel list I got was form my initial all-channels run of the grabber), so your initial diagnosis is correct:  I'm asking for a “non existent” channel.

That probably calls time on this bug.  Thanks.

**Comment by kgroeneveld** [comment]
So which warning were you getting in the end?

With the latest code I would expect something like: "Channel ID 82432 in the current configuration is not found in any enabled lineup."

Or were you still getting the "Use of uninitialized value in sprintf" warning?

>  Will having both channels= lines in add unnecessary load

Not really.  It will use a small (probably negligible) amount of extra memory locally but no extra network traffic if the lineups have not changed.  The grabber actually checks all lineups setup for your account each time as the modified times are all part of a single status command for your account anyway.  I guess when a lineup changes that you aren't actually using it will cause some extra traffic but this currently happens now matter what you have in your config file.

> indeed, will it go wrong if I only have the one channels= but wish to retain both subs?

No.  But the opposite, including a channels= that you don't need can trigger undesired results.  If a channel exists in more than one lineup they could be on different channel numbers.  You could, for example, end up with a terrestrial channel number in your output when you really wanted the satellite channel number.

It is probably fairly rare that you need to include more than one channels= entry.  When I first started using SD several years ago I had to use more than one lineup to cover all the terrestrial channels I could get.  But more recently I can use just one lineup.

**Comment by fnxweb** [comment]
I hadn't tried the latest;  just did, and yes, it gives:

> Channel ID 82432 in the current configuration is not found in any enabled lineup.

As an aside, I did a listings run with each source using just its appropriate `channels=` setting, and now have a slew more “missing” channels.  I'll investigate those and report them to SD at the weekend!
